lrdpv2: Fix an issue with unwinding stack for NON HLOS
Ram dump parser does not support unwinding the stack for NON
HLOS images. In certain cases, we get below exception when
parser tries to dump the context for NON HLOS address. Check
for NON HLOS address and return from the function without
unwinding the frame pointer.

Exception: Invalid stage 1 first- or second-level translation
descriptor: (value: 0x0 {dtype[1:0]=>0x0})
addr: (value: 0x21812010 {base[47:12]=>0x21812, offset[11:3]=>0x2})

Change-Id: I6cacec18574737d0e8261ba1f39dfe2b9b302304